### ISSUE TITLE
Error: global.Olm is not defined

### ISSUE THREAD

**Issue by szimszon** [matrix-hacks/matrix-puppet-facebook#25]
Hi,
I wonder if you could help me.
I try to make a docker container with matrix-puppet-facebook but I can't start it because of this:
```Step 4/6 : RUN cd /opt/matrix-puppet-facebook &&     node index.js -r -u "http://localhost:8090"
 ---> Running in acf5a294e3aa
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
/opt/matrix-puppet-facebook/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                                                                                ^

SyntaxError: /opt/matrix-puppet-facebook/config.json: Unexpected string in JSON at position 231
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:592:27)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/matrix-puppet-facebook/index.js:9:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
ERROR: Service 'mfb' failed to build: The command '/bin/sh -c cd /opt/matrix-puppet-facebook &&     node index.js -r -u "http://localhost:8090"' returned a non-zero code: 7
```

My Dockerfile is:
```
FROM node
RUN cd /opt/ && \
   git clone "https://github.com/matrix-hacks/matrix-puppet-facebook.git" && \
   cd matrix-puppet-facebook && \
   npm install
COPY config.json /opt/matrix-puppet-facebook
RUN cd /opt/matrix-puppet-facebook && \
    node index.js -r -u "http://localhost:8090"
COPY run.sh /
RUN chmod ugo+x /run.sh
```

What could be missing? Thank you!

**Comment by ptman** [comment]
SyntaxError: /opt/matrix-puppet-facebook/config.json: Unexpected string in JSON at position 231

look at your config.json

**Comment by szimszon** [comment]
Thank you. There was a typo in the config indeed.
