### ISSUE TITLE
Error when starting bridge and receving messages

### ISSUE THREAD

**Issue by treethought** [matrix-hacks/matrix-puppet-facebook#30]
Not sure if this is related to the bridge or a more general fb api problem, but upon starting the bridge I receive the following error inside the Facebook Protocol room
```
Error in handleThirdPartyRoomMessage { Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /app/node_modules/facebook-chat-api/utils.js:538:42
    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
    at /app/node_modules/facebook-chat-api/utils.js:523:24
    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
  [name]: 'Error',
  [message]: 'parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.',
  cause: 
   { Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /app/node_modules/facebook-chat-api/utils.js:538:42
    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
    at /app/node_modules/facebook-chat-api/utils.js:523:24
    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
     [stack]: 'Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.\n    at /app/node_modules/facebook-chat-api/utils.js:538:42\n    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)\n    at Function.Promise.attempt.Promise.try (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)\n    at /app/node_modules/facebook-chat-api/utils.js:523:24\n    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)\n    at Promise._settlePromises (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)\n    at Async._drainQueue (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)',
     [message]: 'parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.' },
  isOperational: true,
  [stack]: 'Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.\n    at /app/node_modules/facebook-chat-api/utils.js:538:42\n    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)\n    at Function.Promise.attempt.Promise.try (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)\n    at /app/node_modules/facebook-chat-api/utils.js:523:24\n    at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)\n    at Promise._settlePromises (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)\n    at Async._drainQueue (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)' } { roomId: '1803130974', senderId: '1803130974', text: 'Lol' } 
```

When the bridge starts, I see that a few of my fb friends "join" the room, but every time it's only about 4-6 people and it's usually the same friends each time

**Comment by AndrewJDR** [comment]
facebook-chat-api was updated recently, so please try again with the latest version and reopen if it's still there.
