### ISSUE TITLE
can get into a state wherein messages are received but not sent 

### ISSUE THREAD

**Issue by kfatehi** [matrix-hacks/matrix-puppet-facebook#8]
```
Fri, 17 Feb 2017 20:06:10 GMT matrix-puppet:Base:handleMatrixEvent:info incoming message. data: { age: 83,                                                                                                    content:                                                                                                                                                                                                     { body: 'Ubering to campus. I\'ll be there in say 20 mins',                                                                                                                                                   msgtype: 'm.text' },                                                                                                                                                                                     event_id: '$14873619709152IRPvg:synapse.keyvan.pw',                                                                                                                                                         origin_server_ts: 1487361970308,                                                                                                                                                                            room_id: '!qrPOFNxYlgmpgbkcgv:synapse.keyvan.pw',                                                                                                                                                           sender: '@kfatehi:synapse.keyvan.pw',                                                                                                                                                                       type: 'm.room.message',
  unsigned: { age: 83 },
  user_id: '@kfatehi:synapse.keyvan.pw' }
Fri, 17 Feb 2017 20:06:10 GMT matrix-puppet:Base:getThirdPartyRoomIdFromMatrixRoomId:info reducing array of alases to a 3prid
ERR! Error in getUserInfo { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! Error in getUserInfo   detail:
ERR! Error in getUserInfo    SyntaxError: Unexpected token < in JSON at position 0
ERR! Error in getUserInfo        at Object.parse (native)
ERR! Error in getUserInfo        at /home/keyvan/bridges/facebook/node_modules/facebook-chat-api/utils.js:542:20
ERR! Error in getUserInfo        at tryCatcher (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo        at Function.Promise.attempt.Promise.try (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! Error in getUserInfo        at /home/keyvan/bridges/facebook/node_modules/facebook-chat-api/utils.js:523:24                                                                                            ERR! Error in getUserInfo        at tryCatcher (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo        at Promise._settlePromiseFromHandler (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)                        ERR! Error in getUserInfo        at Promise._settlePromiseAt (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
ERR! Error in getUserInfo        at Promise._settlePromises (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)                                  ERR! Error in getUserInfo        at Async._drainQueue (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in getUserInfo        at Async._drainQueues (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)                                         ERR! Error in getUserInfo        at Immediate.Async.drainQueues (/home/keyvan/bridges/facebook/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getUserInfo        at runCallback (timers.js:637:20)
ERR! Error in getUserInfo        at tryOnImmediate (timers.js:610:5)
ERR! Error in getUserInfo        at processImmediate [as _immediateCallback] (timers.js:582:5),                                                                                                             ERR! Error in getUserInfo   res: '<html><head><title>Redirecting...</title><script>__DEV__=0;_script_path = "XChatUserInfoAsyncController";var uri_re=/^(?:(?:[^:\\/?#]+):)?(?:\\/\\/(?:[^\\/?#]*))?([^?#]*)
(?:\\?([^#]*))?(?:#(.*))?/,target_domain=\'\';window.location.href.replace(uri_re,function(a,b,c,d){var e,f,g;e=f=b+(c?\'?\'+c:\'\');if(d){d=d.replace(/^(!|%21)/,\'\');g=d.charAt(0);if(g==\'/\'||g==\'\\\\
\')e=d.replace(/^[\\\\\\/]+/,\'/\');}if(e!=f){if(window._script_path)document.cookie="rdir="+window._script_path+"; path=/; domain="+window.location.hostname.replace(/^.*(\\.facebook\\..*)$/i,\'$1\');wind
ow.location.replace(target_domain+e);}});</script><script type="text/javascript">/*<![CDATA[*/(function(){function si_cj(m){setTimeout(function(){new Image().src="https:\\/\\/error.facebook.com\\/common\\/scribe_endpoint.php?c=si_clickjacking&t=4369"+"&m="+m;},5000);}if(top!=self && !false){try{if(parent!=top){throw 1;}var si_cj_d=["apps.facebook.com","apps.beta.facebook.com"];var href=top.location.href.t
oLowerCase();for(var i=0;i<si_cj_d.length;i++){if (href.indexOf(si_cj_d[i])>=0){throw 1;}}si_cj("3 https:\\/\\/www.facebook.com\\/");}catch(e){si_cj("1 \\thttps:\\/\\/www.facebook.com\\/");window.document
.write("\\u003Cstyle>body * {display:none !important;}\\u003C\\/style>\\u003Ca href=\\"#\\" onclick=\\"top.location.href=window.location.href\\" style=\\"display:block !important;padding:10px\\">Go to Fac
ebook.com\\u003C\\/a>");/*yOlPz_mY*/}}}())/*]]>*/</script><script>window.location.replace("https:\\/\\/www.facebook.com\\/common\\/invalid_request.php?__req=27");</script><meta http-equiv="refresh" conten
t="0;url=https://www.facebook.com/common/invalid_request.php?__req=27" /></head><body></body></html>' }
Unhandled rejection (<{"error":"JSON.parse error. Check the ...>, no stack trace)
info Got answer in  30819
info Got answer in  13028
```

**Comment by tfreedman** [comment]
I've had this happen to me several times, and it's super annoying because it means you can't trust that messages will actually be sent out without checking Messenger (which defeats the point of using a bridge). Any ETA on a fix?

**Comment by kfatehi** [comment]
I don't have any idea how to reliably replicate this in order to determine how to fix it. The workaround I've been using for the past couple weeks (with what appears to be 100% success) is, and you're probably not going to like this: running an hourly cron that restarts the bridges for which I lack confidence:

```cron
@hourly supervisorctl restart facebook groupme
```

**Comment by tfreedman** [comment]
I just had this happen again. Since restarting matrix-puppet-facebook fixes it, is it possible to just detect the errorDescription and kill the process, so forever can just restart it?

Error in handleMatrixEvent { __ar: 1,
  __sf: 'j0',
  error: 1357004,
  errorSummary: 'Sorry, something went wrong',
  errorDescription: 'Please try closing and re-opening your browser window.',
  payload: null,
  bootloadable: {},
  ixData: {},
  lid: '6449530073281495288',
  [isOperational]: true } { age: 1379,
  content: { body: 'hey', msgtype: 'm.text' },
  event_id: '$:tylerfreedman.com',
  origin_server_ts: 1501648236674,
  room_id: ':tylerfreedman.com',
  sender: '@tyler:tylerfreedman.com',
  type: 'm.room.message',
  unsigned: { age: 1379 },
  user_id: '@tyler:tylerfreedman.com' } ﻿

**Comment by AndrewJDR** [comment]
facebook-chat-api was updated recently, so please try again with the latest matrix-puppet-facebook version and reopen if it's still there.

**Comment by AndrewJDR** [comment]
I've reopened this because I just encountered it. It has been reported several times at the facebook-chat-api group:
https://github.com/Schmavery/facebook-chat-api/issues/555

In https://github.com/matrix-hacks/matrix-puppet-facebook/commit/123efe852a771575ae6a2ff13c32359897db02e8, I've added something that just auto reconnects every 8 hours (give or take). This should hopefully work around the issue.

Obviously there's a better fix here, but I don't see it getting figured out any time soon unless the facebook-chat-api dev's see it in the wild themselves.

**Comment by AndrewJDR** [comment]
The last workaround didn't work, see - https://github.com/Schmavery/facebook-chat-api/issues/555 for details.

Trying https://github.com/matrix-hacks/matrix-puppet-facebook/commit/bb45d7d242ef02616f5231ed1c16a4d68678d27f for a different workaround. This uses a supervisor script and just kills the process altogether periodically. It's an awful hack but the only option right now.
